---
# supported frameworks: mocha|jest|jasmine
framework: mocha

blocklist:
  # format: "<filename>##<suit-name>##<suit-name>##<test-name>"
  - "src/test/api.js"

preRun:
  # set of commands to run before running the tests like `yarn install`, `yarn build`
  command:
    - npm i
    - npm run format:check
    - npm run compile

postMerge:
  pattern:
    - "test/*.ts"
  # strategy for trigerring builds for post-merge
  strategy:
    threshold: 1
    name: after_n_commits

preMerge:
  pattern:
    - "test/*.ts"

# configure whether to smartSelect test-cases. Default true
smartRun: true

# supported tiers: xmall|small|medium|large|xlarge
tier: xsmall

# number of containers in which the tests must be splitted into for execution
parallelism: 2

# version of tas file intended to be used in order to issue warnings for deprecation or breaking changes
version: 1.0.0
